typography_spectrum: 0.9870172657538205
color:
  brandStrength: 0.06205290649086237
  lightness: 0.8930781038943678
  saturation: 0.004370906390249729
  rhythmicContrast: 0.928865252295509
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
layout_spectrum: 0.6751462314277887
author:
  name: Marco Perra
  email: wavefront.explore@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dc7aac2e-cd2c-4c11-92c0-cf5a24d30a2f.png
name: ilab visions
